### PR TITLE
Allow specification of root disk size

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request adds an optional variable to specify the size of the root disk for IPA servers.  The variable's value defaults to 8GB, which is the size of the root disk in the corresponding AMI.

See also cisagov/freeipa-server-tf-module#52.

## 💭 Motivation and context ##

In some cases it makes sense to have more space than the 8GB size of the AMI.

## 🧪 Testing ##

I have successfully applied these changes to our production COOL environment.

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
I will re-run the checks after cisagov/freeipa-server-tf-module#52 is merged, at which point they should pass.

**Review by dav3r — APPROVED** [review]
🚋

**Comment by jsf9k** [comment]
> I will re-run the checks after [cisagov/freeipa-server-tf-module#52](https://github.com/cisagov/freeipa-server-tf-module/pull/52) is merged, at which point they should pass.

Now the checks are failing because we are partway through upgrading Terraform versions.  I will re-run after the dust settles there.

**Comment by dav3r** [comment]
> > I will re-run the checks after [cisagov/freeipa-server-tf-module#52](https://github.com/cisagov/freeipa-server-tf-module/pull/52) is merged, at which point they should pass.
> 
> Now the checks are failing because we are partway through upgrading Terraform versions. I will re-run after the dust settles there.

Yes, I think this PR should just wait until after https://github.com/cisagov/cool-sharedservices-freeipa/pull/43 is merged and it should be fine.

**Review by mcdonnnj — APPROVED** [review]

**Pull request merged**
